first commit
opensergo/opensergo-control-plane pull request #65
Opened 2023-08-10 02:47 UTC by niuniudeadams

### Describe what this PR does / why we need it

### Does this pull request fix one issue?

### Describe how you did it

### Describe how to verify it

### Special notes for reviews

2023-08-10 02:47 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/opensergo/opensergo-control-plane?pullRequest=65) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/opensergo/opensergo-control-plane?pullRequest=65) before we can accept your contribution.<br/><hr/>**changxinzhang** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/opensergo/opensergo-control-plane?pullRequest=65) it.</sub>

2023-10-08 08:38 UTC, SpecialYang requested changes
整体逻辑都没问题。先按意见改一下。
另外把pr的标题从first commint 改成 OSPP2023-{项目id}

2023-10-08 08:38 UTC, SpecialYang commented on control_plane.go
> +	discovery "github.com/envoyproxy/go-control-plane/envoy/service/discovery/v3"
所有的import 都需要保持以下格式

基础库

第三方库

该项目

2023-10-08 08:38 UTC, SpecialYang commented on control_plane.go
> +	cp.xdsServer = transport.NewDiscoveryServer(uint32(8002), []model.SubscribeXDsRequestHandler{cp.handleXDSSubscribeRequest})
这个端口是你自定义的？

2023-10-08 08:38 UTC, SpecialYang commented on pkg/model/xDS_connection.go
> +	if conn.WatchedResources != nil && conn.WatchedResources[typeUrl] != nil {
WatchedResources 不会有nil的情况

2023-10-08 08:38 UTC, SpecialYang commented on control_plane.go
> +				Kind:      request[0] + delimiter + request[1] + delimiter + request[2],
这里 数字的可维护性太差了，建议弄一个函数包一下。
namespace, appname, kind := tool(xxxx)

2023-10-08 08:38 UTC, SpecialYang commented on control_plane.go
> +			c.xdsServer.AddConnectionToMap(request[4], request[3], request[0]+"/"+request[1]+"/"+request[2], con)
这里同理，建议，在最上面提前计算好

2023-10-08 08:38 UTC, SpecialYang commented on k8s/rbac/rbac.yaml
> -
没必要的改动

2023-10-08 08:38 UTC, SpecialYang commented on pkg/main/main.go
>  import (
以下所有的改动，都没必要

2023-10-08 08:38 UTC, SpecialYang commented on pkg/transport/grpc/xDSServer.go
> +		// and often very cheap to handle (simple ACK), so we check it first.
这个注释没必要了

2023-10-08 15:14 UTC, niuniudeadams commented on control_plane.go
> +	cp.xdsServer = transport.NewDiscoveryServer(uint32(8002), []model.SubscribeXDsRequestHandler{cp.handleXDSSubscribeRequest})
是的，因为我看原项目也是固定端口是10246，所以我就写了8002

2023-10-09 01:50 UTC, SpecialYang commented on control_plane.go
> +	cp.xdsServer = transport.NewDiscoveryServer(uint32(8002), []model.SubscribeXDsRequestHandler{cp.handleXDSSubscribeRequest})
你看看10248 有没有用？没有，就用这个吧

2023-10-09 01:51 UTC, niuniudeadams commented on control_plane.go
> +	cp.xdsServer = transport.NewDiscoveryServer(uint32(8002), []model.SubscribeXDsRequestHandler{cp.handleXDSSubscribeRequest})
好的，我看一下

2023-10-10 02:19 UTC, SpecialYang commented on k8s/rbac/rbac.yaml
> -
这里的改动是什么？

2023-10-10 03:47 UTC, niuniudeadams commented on k8s/rbac/rbac.yaml
> -
我可能删了第一个空行，导师

2023-10-10 03:53 UTC, SpecialYang approved these changes
LGTM.

2023-10-14 04:19 UTC, merged